### ISSUE TITLE
Veraltete mpdf/mpdf Version

### ISSUE THREAD

**Issue by designpilot** [do-while/contao-mpdf-template-bundle#1]
Hallo Hagen

In deiner **contao-mpdf-template-bundle** hat es eine Komponente mpdf/mpdf in welcher die **setasign/fpdi** in **Version 1.6.*** enthalten ist. Eine Erweiterung von Sven Rhinow (srhinow) die wie folgt heisst **srhinow/projekt-manager-bundle** verlangt die **setasign/fpdi 2.0** oder höher.

Wie kann ich trotzdem deine Erweiterung nutzen ??? Weil so im Moment kann ich nur **contao-mpdf-template-bundle** oder **srhinow/projekt-manager-bundle** nutzen, aber nicht beide. In deiner Erweiterung ist die **setasign/fpdi 1.6.*** enthalten die aus der **mpdf/mpdf 7.0** kommt. Die Erweiterung **srhinow/projekt-manager-bundle** beinhaltet dann aber die neuere **setasign/fpdi 2.0** wie kann das gelöst werden.

**Comment by do-while** [comment]
Hallo,
das tut mir leid. Im Moment liegt es an dem mpdf-Projekt, dass ich einbinde.
mpdf seinerseits verwendet setasign/fpdi Version 1.6, es liegt also an der composer.json im mpdf-Projekt.
Hier gibt es leider noch keinen Update.

**Comment by designpilot** [comment]
Nützt das was wenn man bei mpdf durchklingelt (eine mail sendet und darum bittet das setasign/fpdi auf min. Version 2.0 angehoben wird????)

**Comment by do-while** [comment]
Man kann es probieren, ansonsten gibt es dazu bereits ein Ticket

**Comment by zonky2** [comment]
require steht auf `^2.1`
https://github.com/mpdf/mpdf/blob/development/composer.json#L40

@do-while Ticket sollte sich erledigt haben...
