### ISSUE TITLE
Warning with PHP 8

### ISSUE THREAD

**Issue by zonky2** [do-while/contao-mpdf-template-bundle#10]
`$language` not set

see https://github.com/do-while/contao-mpdf-template-bundle/blob/3ab155b8aa750331e711e17e6bdf49bac1f39fc7/src/Resources/contao/classes/mpdf_hookControl.php#L176
and https://github.com/do-while/contao-mpdf-template-bundle/blob/3ab155b8aa750331e711e17e6bdf49bac1f39fc7/src/Resources/contao/classes/mpdf_hookControl.php#L189

no idea where the info should come from...

**Comment by do-while** [comment]
Ist bisher nicht aufgefallen :-)
In der 1.6.2 behoben
