### ISSUE TITLE
Sprache nicht korrekt

### ISSUE THREAD

**Issue by eiswurm** [do-while/contao-mpdf-template-bundle#11]
Wir haben festgestellt, das bei uns die Silbentrennung mittels CSS (hyphens: auto) nicht korrekt funktioniert. Es liegt wohl daran, das beim PDF-Export
```php
$objmPdfTpl->language = $language; 
``` 
nicht korrekt funktioniert. Wenn wir in der mpdf_hookControl.php folgenden Code ergänzen geht es:

```php
$pdf->SHYlang = 'de';
$pdf->SHYleftmin = 3;
```
Kann das jemand nachvollziehen?

**Comment by do-while** [comment]
Ist jetzt in der Version 1.7.0 implementiert
