### ISSUE TITLE
Event BeforeOutputArticleAsPdfEvent is not triggered

### ISSUE THREAD

**Issue by dmolineus** [do-while/contao-mpdf-template-bundle#13]
The commit unfortunately removed the trigger of the `BeforeOutputArticleAsPdfEvent`. Any reason why to drop it again?

https://github.com/do-while/contao-mpdf-template-bundle/commit/07cac3ea1918d24d659bef8f3476ee2ed02b066f#diff-3a59910badd3caff9f85164b00de9371579ea494cf4d32688530e1391cf5c0d7L232-L235

**Comment by do-while** [comment]
Es fehlten ein paar Zeilen Code - Sorry, das muss bei meinen zusätzlichen Änderungen passiert sein.
=> neues Release 1.7.1
