### ISSUE TITLE
Konfigurierbare PDF_PAGE_ORIENTATION 

### ISSUE THREAD

**Issue by Joam55** [do-while/contao-mpdf-template-bundle#2]
Hallo Hagen,
es wäre schön die Extension würde möglichst nicht einfach nur die PDF_PAGE_ORIENTATION Konstante von Contao bzw. dem contao/tcpdf-bundle nehmen, sondern dass es in irgendeiner Form konfigurierbar ist (mit Fallback auf die Konstante).
Gruß
dtptiger
[https://community.contao.org/de/showthread.php?74025-Meine-PDF_PAGE_ORIENTATION-wird-immer-wieder-überschrieben](url)

**Comment by zonky2** [comment]
Link mit richtiger URL
https://community.contao.org/de/showthread.php?74025-Meine-PDF_PAGE_ORIENTATION-wird-immer-wieder-überschrieben

**Comment by zonky2** [comment]
@Joam55 hier wird die Seitenorientierung nach mPDF übernommen
https://github.com/do-while/contao-mpdf-template-bundle/blob/master/src/Resources/contao/classes/mpdf_hookControl.php#L112

könnte man leicht an der Stelle gegen eine eigene DCA-Konfiguration mit `L` und `P` austauschen

**Comment by fritzmg** [comment]
Wie schon im Thread erwähnt kann man das einfach mit einer eigenen `contao/config/config.php` machen - da diese inkludiert wird, bevor die `tcpdf.php` inkludiert wird.

**Comment by zonky2** [comment]
somit wäre das was für die Readme/Doku (@do-while)

**Comment by do-while** [comment]
Für die Seitenorientierung und andere Neuerungen gibt es hier im GitHub-Wiki eine aktualisierte Version.
