### ISSUE TITLE
Datei "/files/mpdf.css" per Dateipicker einbinden

### ISSUE THREAD

**Issue by zonky2** [do-while/contao-mpdf-template-bundle#3]
die Datei `mpdf.css` wird nicht unter /files abgelegt - im Repo habe ich diese auch nicht gefunden...?

ggf. wäre es schöner, einen Unterordner `/mpdf` anzulegen oder per Picker die Datei aus eigenem Theme-Ordner auswählbar zu machen

**Comment by zonky2** [comment]
@do-while jetzt habe ich es glaube ich verstanden - die Datei wird gar nicht mitgeliefert, sondern nur automatisch übernommen, wenn vorhanden....

dann wäre mir ein Dateipicker lieber und man kann die Datei mit in den Theme-Ordner packen

**Comment by fritzmg** [comment]
See https://github.com/do-while/contao-mpdf-template-bundle/pull/4 ;)

**Comment by do-while** [comment]
Ab Version 1.2 können eigene CSS-Dateien mit eingebunden werden.
Die Verwendung der PDF-Vorlage ist jetzt optional.

Danke an @fritzmg für die Vorbereitung durch Pull-Request.
