### ISSUE TITLE
PDF-Dateinamen ändern

### ISSUE THREAD

**Issue by denniserdmann** [do-while/contao-mpdf-template-bundle#6]
Moin!

Ich setze die Erweiterung innerhalb eines Produktkatalogs ein und würde gerne die Dateinamen nach einem Schema **Produktname-Artikelnr.pdf** frei bestimmen. Standardmäßig wird ja der Artikel-Titel genommen, [siehe hier](https://github.com/do-while/contao-mpdf-template-bundle/blob/master/src/Resources/contao/classes/mpdf_hookControl.php#L171).

Gibt es eine Möglichkeit, den Dateinamen zu ändern/manipulieren?

Viele Grüße,
Dennis

**Comment by do-while** [comment]
Hallo Dennis,

leider ist der Dateiname bisher fest an den Artikel-Titel gekoppelt.
Wie würdest Du das brauchen?
Eine Angabe im Startpunkt, wo die anderen Parameter sind, ist sicherlich nicht sinnvoll. Dann müßte man das eher in den Artikeleigenschaften angeben können. Die Standard-Syndication hatte das auch nicht, deshalb bin ich bisher nicht drauf gekommen.

Den Artikel-Titel kannst Du nicht so verändern, dass der immer stimmt?

**Comment by denniserdmann** [comment]
Ich habe ein Projekt, in dem Custom Catalog die Produkte über ein Reader-Modul ausgibt. Ich habe schon versucht, den Artikel-Titel zu manipulieren, aber das scheint nicht so schön zu gehen, wie beispielsweise der Seitentitel.

Ich habe mir das schon fast gedacht, aber da du dich mit der PDF-Generierung ja deutlich besser auskennst, dachte ich, dass ich vielleicht was übersehen habe.

**Comment by do-while** [comment]
Würde Dir ein Hook was nützen? oder ist das zu viel Aufwand den Hook zu bedienen?

**Comment by denniserdmann** [comment]
Unter Umständen ja. Ich könnte den Link zur PDF-Generierung theoretisch doch auch im Template des Lesers einfügen, oder? Wenn ich die Möglichkeit hätte, nicht (nur) die ID des Artikels zu übergeben, sondern auch einen Dateinamen, müsste es gehen.

Also 

```
<a href="http://domain.de/kategorie/produktalias.html?pdf=256&produktname"></a>
```

**Comment by do-while** [comment]
Der Aufrufparameter gefällt mir!
Die neue Version 1.3.0 ist verfügbar, Doku siehe
https://github.com/do-while/contao-mpdf-template-bundle/wiki/mpdf-template-f%C3%BCr-Contao-4.4-(DE)

**Comment by denniserdmann** [comment]
Top! 👍
