### ISSUE TITLE
Merkwürdiges Problem bei der PDF-Ausgabe / Erstellung mit einem " in der Überschrift

### ISSUE THREAD

**Issue by aow-de** [do-while/contao-mpdf-template-bundle#7]
Hallo und ein frohes neues Jahr zusammen.
Ich habe ein sehr, sehr merkwürdiges Problem bei der PDF-Ausgabe mit dem mpdf-template-bundle und der Produktdatenbank meines Kunden. In den Produktdaten taucht - an mehreren Stellen ein " als Zeichen für "Zoll" (als Maß) auf. In diversen Produktdatentabellen aber auch in der jeweiligen Produktbezeichnung. Diese wird im erzeugten PDF bzw. auf der entsprechenden Produktseite / Artikel als erstes ausgegeben.
Im HTML Quelltext ist das " auch korrekt mit `&#34;` als UTF Code angegeben / ausgezeichnet. Dennoch scheint mpdf damit ein Problem zu haben, denn danach wird nur noch das Produktbild ausgegeben, Produkttext sowie Datentabellen "verschwinden" bzw. sind nicht im PDF, ebenso eine zugehörige Legendenskizze nicht, dafür aber der dann folgende Legendentext bzw. die Erklärung.
Ändere ich in der Datenbank das " (`&#34;`) zu einem ” (deutsches/schräges Anführungszeichen oben), welches so auch 1:1 als Text in der DB steht (also keine Umwandlung in Code / HTML Entity o.ä.), dann funktioniert die Ausgabe reibungslos, selbst wenn im direkt folgenden Produkttext ebenfalls wieder Maße in Zoll und mit dem " kommen. Mache ich das "on the fly", indem ich per str_replace vor der eigentlichen HTML Ausgabe das `&#34;` durch das ” (oder auch Zoll ausgeschrieben) ersetze, dann bleibt der Fehler bei der Ausgabe dennoch bestehen...
So etwas merkwürdiges habe ich noch nicht gesehen, tbh. Ich muss also im Backend / in der Datenbank jetzt alle " durch ” per Hand austauschen, dann funktioniert die Ausgabe (egal wie viele normale " danach noch kommen). Aber das ist natürlich nur ein Workaround - keine wirkliche Lösung.
Hat evtl. irgendjemand hier eine Idee?!?

**Comment by do-while** [comment]
Hallo,
ich habe es nicht geschafft, diese Situation nachzustellen (Contao 4.9). Welche Contaoversion verwendest Du?
In der 4.9 bei den Sicherheitsupdates sind gerade in dem Bereich einige Anpassungen gewesen, die in den schnell folgenden Releases dann repariert wurden. Hast Du vielleicht nicht die aktuelle Contaoversion?

**Comment by aow-de** [comment]
Hallo,
ich habe es gerade - nach Update & Fehlerbeseitigung beim Catalog Manager - nochmals getestet, das merkwürdige Verhalten beim PDF (mpdf) bleibt (wollte Bug beim CM hier vorher möglichst ausschließen).
Contao in letzter LTS Version (v 4.9.24) und mpdf-template in der v 1.4.0.
Anbei drei JPEGs der PDF Ausgabe. 1x korrekte Ausgabe (2-Seiten) bei Nutzung von ” in der Überschrift / Artikelbezeichnung und danach dieses nicht zu verstehende Ergebnis, wenn ich das normale " (`&quot;`oder eben auch `&#34;`) für die Zoll Einheitsangabe nutze.

Die Seite an sich findest Du unter redesign.ludemann.info, Produktübersicht und dann einen Artikel auswählen (hier als Muster war Y-Fom, Flansch, DIN, Grauguss, PN 16 Standard). Ich habe bei dem jetzt - damit Du es live sehen kannst - den "Bug" (sprich das normale Anführungszeichen) in der NL-Version bzw. Beschreibung eingebaut. Sprachwechsel zu NL führt dann also dazu, dass Du bei der PDF Ausgabe genau den unten gezeigten Fehler auch haben müsstest, während deutsche / englische Version (mit ”) problemlos funktionieren.

Was ich überhaupt nicht verstehe, ist, dass er beim Fehler noch das Bild ausgibt sowie dann den Legendentext, der eigentlich auf Seite 2 kommt. Es fehlen aber die Datentabellen und das Bild der Legende selber, die nix mit der Datenbankabfrage da oben zu tun haben (sind eigene Module oder "Artikelbestandteile" in Contao)... Das erste "Datenbankmodul" gibt Überschrift, Artikelbild und eben Werkstoffe, Anschluss etc. aus. Danach dann Tabellen etc. über getrennte / eigene Module und Inhalte.

![korrekte-PDF-Ausgabe-1](https://user-images.githubusercontent.com/96884194/147882898-84d457c5-d429-43aa-b29f-acb58226f75c.jpg)
![korrekte-PDF-Ausgabe-2](https://user-images.githubusercontent.com/96884194/147882908-a3d10584-8111-4f07-b804-5ce07815fecb.jpg)
![fehlerhafte-PDF-Ausgabe](https://user-images.githubusercontent.com/96884194/147882916-d9f9470a-658e-4428-a772-1852b4d7e024.jpg)

**Comment by aow-de** [comment]
Hallo Herr Klemp,
zu später Stunde habe ich endlich den Fehler / die Ursache für das Problem gefunden! 
Es war nicht der Text mit " im h2-tag, sondern die Nutzung (auch per DB Abfrage und ebenfalls mit HTML- bzw. UTF-Entity im Quelltext) im alt-Text des zugehörigen Bildes. Hier scheint mpdf ein Problem zu haben, denn dieser alt-Text im Quellcode führt dann zum Abbruch der Ausgabe bzw. das korrekt codierte " scheint als "Ende" des alt-Textes vom Bild interpretiert zu werden und dementsprechend ist der HTML-Code danach für den Interpreter "falsch" - bis zum nächsten alt-Tag, der dann korrekt geschlossen wird. Daher auch das oben sichtbare, vorher unerklärliche Verhalten bzw. die merkwürdige Ausgabe des Legendentextes nach dem nächsten (fehlenden) Bild.
Also falls das in Ihrer Erweiterung irgendwo "abgefangen" werden kann, dann wissen Sie jetzt wo der Fehler liegt. ;)
Damit machen ich die Issue hier auch zu. Problem gefunden und mit anderen alt-Texten bei den Bildern behoben.
