### ISSUE TITLE
Tausende leere Seiten als PDF-Ausgabe

### ISSUE THREAD

**Issue by eberhardalbrecht** [do-while/contao-mpdf-template-bundle#9]
Hallo,
ich verwende die Erweiterung mPDF-Template schon länger bei der Webseite (https://www.oeku-buero.de/). Die Verwendung ist auch ganz normal, den Besuchern der Webseite wird die Möglichkeit geboten, Artikel als PDF zu speichern. Dazu gibt es am "Startpunkt einer Webseite" eine Vorlagendatei und Eingabewerte für die Randbereiche. Jetzt ist mir zufällig aufgefallen, dass inzwischen PDF-Dateien von mehreren Tausend Seiten erzeugt werden. Diese PDF-Dateien sind leer, d.h. es ist jeweils nur die um viele Seiten verlängerte Vorlagendatei.
Ich vermute, das Problem ist mit der neuesten Version von mPDF-Template entstanden.
Ich habe etwas herum getestet, die Situationhat sich aber nicht verändert.
Den beschriebenen Effekt kann man sich an der Webseite (https://www.oeku-buero.de/) anschauen.
Ich bin gespannt auf ihre Antwort und grüße Sie
Eberhard Albrecht

**Comment by landzone21** [comment]
Das gleiche Problem hab ich auch auf einer Kundenwebsite, es werden über 300 leere PDF-Seiten mit der Vorlagendatei generiert, aber ohne dynamischen Inhalt. Gibt es hier inzwischen eine Lösung?

**Comment by do-while** [comment]
Ich habe das heute mal in einer aktuellen 4.13 mit PHP 8.1 ausprobiert. Bei mir funktioniert es, wie es soll.
Habt Ihr denn die Ränder auch korrekt angegeben und die Einheit dahinter auf mm oder cm gestellt?

Ich vermute, dass Ihr bei falscher Einstellung Ränder habt, die nahezu keinen Inhalt zulassen und so der Text buchstabenweise untereinander gerendert wird, bzw. die Bilder irgendwie sehr lang werden.

**Comment by landzone21** [comment]
Danke, ich konnte das Problem inzwischen lösen, es lag tatsächlich an den Einstellungen der Ränder. Die Inhalte auf der Website hatten sich geändert, dadurch passten die Ränder nicht mehr und es wurden gar keine Inhalte mehr gerendert.

**Comment by rustykowski** [comment]
Hallo Hagen,
bei mir sind es nicht Tausende Seiten, nur Dutzende.
Das Problem tritt sowohl mit der Bundle-Version 1.5.2 (Contao 4.9, PHP 7.4) auf, als auch mit dem Bundle 1.6.0 (Contao 4.13, PHP 8.2). In irgendeiner früheren Version funktionierte schon mal alles.

- Auf die Randeinstellungen habe ich geachtet.
- Ohne Erfolg habe ich auch schon einmal probiert, meine CSS-Datei wegzulassen.
- Die pure "PDF-Artikel"-Funktion ohne mPDF-Template generiert lesbare unformatierte PDFs.
- Mit mPDF-Template erhalte ich jedoch viele leere Seite ohne jeden Textinhalt.

Gerade entdecke ich, dass alle funktioniert, wenn ich die Einstellungen zur PDF-Vorlage in jedem einzelnen Artikel vornehme. Die Einstellungen im Startpunkt werden offenbar nicht richtig übernommen.

**Comment by eberhardalbrecht** [comment]
Hallo,
ich habe inzwischen eine Lösung für mein Problem gefunden. Es lag bei mir an den Randeinstellungen. Bei den Randeinstellungen kann man die Maßeinheiten cm und mm auswählen. Ich habe inzwischen herausgefunden, dass die eingegebenen Zahlen, anders als in früheren Versionen, immer als cm interpretiert werden. Bei mir waren aber teilweise 30 (mm) eingestellt. Wenn ich dies berücksichtige, d.h. 3 (cm) eingebe, habe ich keine Probleme mehr mit der Erweiterung mPDF-Template und nutze sie weiter gerne.
Viele Grüße von 
Eberhard Albrecht

**Comment by rustykowski** [comment]
Danke @eberhardalbrecht, sehr gut!
Nach Umstellung auf cm klappt es bei mir auch mit der Einstellung in der Root-Seite. 

@do-while  öffnest du das Ticket wieder?

**Comment by do-while** [comment]
Das ist ein sehr hilfreicher Hinweis, dann sind wahrscheinlich die Maße so berechnet worden, dass kein Platz auf der Seite war und dadurch eine Seite nach der anderen erzeugt wurde. Da werde ich ein neues Release machen ...

**Comment by do-while** [comment]
Ich konnte das Problem nachstellen und habe den Quellcode korrigiert.
Neues Release 1.6.1 ist im Contao-Manager verfügbar.
